// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectInvite = `-- name: CreateProjectInvite :one
INSERT INTO project_invites (project_id, email, token, role, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, email) DO UPDATE SET token = EXCLUDED.token, role = EXCLUDED.role, expires_at = EXCLUDED.expires_at
RETURNING id, project_id, email, token, role, created_at, expires_at
`

type CreateProjectInviteParams struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	Role      string             `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateProjectInvite(ctx context.Context, arg CreateProjectInviteParams) (ProjectInvite, error) {
	row := q.db.QueryRow(ctx, createProjectInvite,
		arg.ProjectID,
		arg.Email,
		arg.Token,
		arg.Role,
		arg.ExpiresAt,
	)
	var i ProjectInvite
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteProjectInvite = `-- name: DeleteProjectInvite :exec
DELETE FROM project_invites
WHERE id = $1
`

func (q *Queries) DeleteProjectInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectInvite, id)
	return err
}

const getProjectInviteByToken = `-- name: GetProjectInviteByToken :one
SELECT id, project_id, email, token, role, created_at, expires_at FROM project_invites
WHERE token = $1
`

func (q *Queries) GetProjectInviteByToken(ctx context.Context, token string) (ProjectInvite, error) {
	row := q.db.QueryRow(ctx, getProjectInviteByToken, token)
	var i ProjectInvite
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listProjectInvites = `-- name: ListProjectInvites :many
SELECT id, project_id, email, token, role, created_at, expires_at FROM project_invites
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectInvites(ctx context.Context, projectID pgtype.UUID) ([]ProjectInvite, error) {
	rows, err := q.db.Query(ctx, listProjectInvites, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectInvite
	for rows.Next() {
		var i ProjectInvite
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Email,
			&i.Token,
			&i.Role,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
