// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteTicket(ctx context.Context, id pgtype.UUID) error
	GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error)
	GetTicketByID(ctx context.Context, id pgtype.UUID) (Ticket, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListProjectsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Project, error)
	ListTicketsByProject(ctx context.Context, projectID pgtype.UUID) ([]Ticket, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
