// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (project_id, title, description, status, priority, assignee_id, parent_id, creator_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, title, description, status, priority, assignee_id, created_at, updated_at, parent_id, creator_id, deleted_at
`

type CreateTicketParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	Priority    string      `json:"priority"`
	AssigneeID  pgtype.UUID `json:"assignee_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	CreatorID   pgtype.UUID `json:"creator_id"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.ParentID,
		arg.CreatorID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.CreatorID,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
UPDATE tickets SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTicket, id)
	return err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, project_id, title, description, status, priority, assignee_id, created_at, updated_at, parent_id, creator_id, deleted_at FROM tickets WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTicketByID(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.CreatorID,
		&i.DeletedAt,
	)
	return i, err
}

const listTicketsByProjectAndUser = `-- name: ListTicketsByProjectAndUser :many
SELECT t.id, t.project_id, t.title, t.description, t.status, t.priority, t.assignee_id, t.created_at, t.updated_at, t.parent_id, t.creator_id, t.deleted_at FROM tickets t
JOIN project_members pm ON t.project_id = pm.project_id
WHERE t.project_id = $1 AND pm.user_id = $2 AND t.deleted_at IS NULL
  AND (
    pm.role IN ('admin', 'owner')
    OR t.assignee_id = $2
    OR (t.creator_id = $2 AND t.assignee_id IS NULL)
  )
ORDER BY t.created_at DESC
`

type ListTicketsByProjectAndUserParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListTicketsByProjectAndUser(ctx context.Context, arg ListTicketsByProjectAndUserParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByProjectAndUser, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.CreatorID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET title = $2,
    description = $3,
    status = $4,
    priority = $5,
    assignee_id = $6,
    parent_id = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, description, status, priority, assignee_id, created_at, updated_at, parent_id, creator_id, deleted_at
`

type UpdateTicketParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	Priority    string      `json:"priority"`
	AssigneeID  pgtype.UUID `json:"assignee_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.ParentID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.CreatorID,
		&i.DeletedAt,
	)
	return i, err
}
