// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (project_id, title, description, status, priority, assignee_id, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, title, description, status, priority, assignee_id, created_at, updated_at, parent_id
`

type CreateTicketParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	Priority    string      `json:"priority"`
	AssigneeID  pgtype.UUID `json:"assignee_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.ParentID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTicket, id)
	return err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, project_id, title, description, status, priority, assignee_id, created_at, updated_at, parent_id FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}

const listTicketsByProject = `-- name: ListTicketsByProject :many
SELECT id, project_id, title, description, status, priority, assignee_id, created_at, updated_at, parent_id FROM tickets WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTicketsByProject(ctx context.Context, projectID pgtype.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET title = $2,
    description = $3,
    status = $4,
    priority = $5,
    assignee_id = $6,
    parent_id = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, description, status, priority, assignee_id, created_at, updated_at, parent_id
`

type UpdateTicketParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	Priority    string      `json:"priority"`
	AssigneeID  pgtype.UUID `json:"assignee_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.ParentID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}
