// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (project_id, title)
VALUES ($1, $2)
RETURNING id, project_id, title, is_completed, created_at, updated_at
`

type CreateTodoParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Title     string      `json:"title"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.ProjectID, arg.Title)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, project_id, title, is_completed, created_at, updated_at FROM todos WHERE id = $1
`

func (q *Queries) GetTodoByID(ctx context.Context, id pgtype.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodosByProject = `-- name: ListTodosByProject :many
SELECT id, project_id, title, is_completed, created_at, updated_at FROM todos WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTodosByProject(ctx context.Context, projectID pgtype.UUID) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $2,
    is_completed = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, is_completed, created_at, updated_at
`

type UpdateTodoParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	IsCompleted bool        `json:"is_completed"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo, arg.ID, arg.Title, arg.IsCompleted)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
